version: '3'

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=jsconsultores
      - POSTGRES_PASSWORD=Admin123
      - POSTGRES_DB=dbjs
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata

  web:
    build: ./JSIncidentManagement
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./JSIncidentManagement:/JSIncidentManagement
    ports:
      - "8000:8000"
    depends_on:
      - db


volumes:
  db_data:
    external: true
